- name: Setup common softwares
  hosts: local

  tasks:
    - name: Install Google Chrome
      shell: brew install --cask google-chrome
      args:
        creates: "/Applications/Google Chrome.app"

    - name: Install Visual Studio Code
      shell: brew install --cask visual-studio-code
      args:
        creates: "/Applications/Visual Studio Code.app"

    - name: Clean up brew, remove any older versions from the cellar
      shell: brew cleanup
