- name: Setup essential softwares
  hosts: local

  tasks:
    - name: Check if Homebrew is installed on Apple Silicon
      stat:
        path: /opt/homebrew/bin/brew
      register: brew_binary

    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Sources/theme
        - ~/Projects

    - name: Copy configuration files
      copy:
        src: "{{item}}"
        dest: ~/Sources
      with_items:
        - static/spaceship-operator-mono.zsh-theme

    - name: Install git
      homebrew:
        name: git
        state: present

    - name: Install openssl
      homebrew:
        name: openssl
        state: present

    - name: Install Node.js 18
      homebrew:
        name: node@18
        state: present
        link: true

    - name: Install specific version of Yarn
      homebrew:
        name: yarn@1.22.22
        state: present

    - name: Deep Theme colors for iTerm
      template:
        src: ./static/geek.itermcolors
        dest: ~/Sources/theme/geek.itermcolors

    - name: Clone oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: "~/Sources/oh-my-zsh"
        update: no

    - name: Install spaceship-operator-mono theme for Zsh
      copy:
        src: ./static/spaceship-operator-mono.zsh-theme
        dest: ~/Sources/oh-my-zsh/custom/themes/spaceship-operator-mono.zsh-theme

    - name: Install Auto suggestions plugin for Zsh
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/Sources/oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install Syntax highlighting plugin for Zsh
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: ~/Sources/oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Create ~./oh-my-zsh symlink
      file:
        path: ~/.oh-my-zsh
        src: ~/Sources/oh-my-zsh
        state: link

    - name: Copy .zshrc to user's Home
      template:
        src: ./static/.zshrc
        dest: ~/.zshrc
        force: no

    - name: Set Zsh as the default shell!
      become: true
      become_method: sudo
      user: 
        name: '{{ansible_user}}'
        shell: /bin/zsh

    - name: Add Homebrew to PATH in zsh config
      blockinfile:
        path: ~/.zshrc
        marker: "# {mark} HOMEBREW PATH"
        block: |
          eval "$(/opt/homebrew/bin/brew shellenv)"
      when: brew_binary.stat.exists