- name: Setup essential softwares
  hosts: local

  tasks:
    - name: Check if Homebrew is already installed
      stat:
        path: /opt/homebrew/bin/brew
      register: brew

    - name: Install Homebrew
      shell: |
        yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew.stat.exists
