- name: Initialize before setup
  hosts: local
  vars_prompt:
    - name: become_pass
      prompt: "Enter sudo password"
      private: yes
      unsafe: yes

  tasks:
    - name: Get username from system
      become: false
      command: whoami
      changed_when: false
      register: username_result

    - name: Set facts (user + sudo password)
      set_fact:
        ansible_user: "{{ username_result.stdout }}"
        ansible_become_pass: "{{ become_pass }}"
      no_log: true

    - name: Verify sudo access
      become: true
      command: whoami
      changed_when: false