- name: Initialize before setup
  hosts: local
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter sudo password (required for installations)"
      private: yes

  tasks:
    - name: Get username from system
      become: false
      command: whoami
      changed_when: false
      register: username_result

    - name: Set ansible user fact
      set_fact: 
        ansible_user: "{{username_result.stdout}}"

    - name: Verify sudo access
      become: true
      command: whoami
      changed_when: false
      register: sudo_check