- name: Node.js
  hosts: local

  tasks:
    - name: Download Nvm installation script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        dest: ~/Sources/nvmInstaller.sh

    - name: Install Nvm
      shell: "bash ~/Sources/nvmInstaller.sh"
      args:
        creates: ~/.nvm/nvm.sh

    - name: Install Node.js version
      shell: |
        source ~/.nvm/nvm.sh
        nvm install 20.15.0 && nvm alias default 20.15.0
      args:
        executable: /bin/zsh
        creates: ~/.nvm/versions/node

    - name: Install yarn
      shell: brew install yarn --ignore-dependencies
