- name: Setup Dependencies for React Native
  hosts: local

  tasks:
    - name: Install watchman
      shell: brew install watchman

    - name: Install cocoapods
      shell: brew install cocoapods
