- name: Setup Dependencies for React Native
  hosts: local

  tasks:
    - name: Install watchman
      shell: brew install watchman

    - name: Install cocoapods
      shell: brew install cocoapods

    # - name: Check if ruui-cli exists
    #   shell: ruui --version
    #   register: ruuiVersion
    #   ignore_errors: yes
    #   no_log: True

    # - name: Install ruui-cli
    #   shell: npm i -g ruui-cli
    #   when: ruuiVersion.failed == True
